baseURL = 'https://weiren.org/'
languageCode = 'zh-tw'
title = 'Wet / Rain'
theme = 'PaperMod'

[params]
  ShowPostNavLinks = true
  defaultTheme = "auto"
  disableThemeToggle = false

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[[menu.main]]
  name = "Home | é¦–é "
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts | æ–‡ç« "
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags | æ¨™ç±¤"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Categories | åˆ†é¡"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "About | é—œæ–¼é€™è£¡"
  url = "/about/"
  weight = 5

[[menu.main]]
  identifier = "search"
  name = "ğŸ” æœå°‹"
  url = "/search/"
  weight = 10
